
CREATE TABLE MEDICOS (
    ID_MED INT auto_increment  PRIMARY KEY,
    NOMBRE_MED VARCHAR(100)
);

CREATE TABLE DIAS(
	DIA_D VARCHAR(20) PRIMARY KEY
);

CREATE TABLE DIASXMEDICOS(
	ID_DIAXMED INT,
    DIA_DIAXMED VARCHAR(20),
    PRIMARY KEY (ID_DIAXMED,DIA_DIAXMED)
);

CREATE TABLE HORARIOMEDICOS(
	IDMED_HRXMED INT,
    HRINICO_HRXMED time,
    HRFIN_HRXMED time,
    primary key(IDMED_HRXMED,HRINICO_HRXMED,HRFIN_HRXMED)
);

INSERT INTO MEDICOS(NOMBRE_MED)
SELECT "CARLOS";

/*CARGAR TODOS LOS DIAS DE LAS SEMANA*/
INSERT INTO DIAS(DIA_D)
VALUE ("DOMINGO");

/*ASIGNAR LOS DIAS A LOS MEDICOS*/
INSERT INTO diasxmedicos(ID_DIAXMED,DIA_DIAXMED)
VALUE(1,"VIERNES");

/*ASIGNAR LOS HORARIOS A LOS MEDICOS*/
INSERT INTO HORARIOMEDICOS(IDMED_HRXMED,HRINICO_HRXMED,HRFIN_HRXMED)
value(1,'08:00:00','16:00:00');

SELECT * FROM DIASXMEDICOS;

SELECT * FROM HORARIOMEDICOS;

SELECT NOMBRE_MED, DIA_DIAXMED,HRINICO_HRXMED AS HORAINICIO, HRFIN_HRXMED AS HORAFIN FROM MEDICOS JOIN DIASXMEDICOS ON MEDICOS.ID_MED = DIASXMEDICOS.ID_DIAXMED JOIN HORARIOMEDICOS ON MEDICOS.ID_MED = IDMED_HRXMED;

CREATE TABLE TURNOS(
	ID_TURNO INT auto_increment primary KEY,
    IDESP_TURNO VARCHAR(100),
    DNIMED_TURNO INT,
    IDESTADO_TURNO INT,
    DNIPAC_TURNO BIGINT,
    FECALT_TURNO date ,
    HRINICIO_TURNO VARCHAR(100),
    HRFIN_TURNO VARCHAR(100)
);

drop table HORARIOMEDICOS;

SELECT NOMBRE_MED, DIA_DIAXMED,HRINICO_HRXMED AS HORAINICIO, HRFIN_HRXMED AS HORAFIN FROM MEDICOS JOIN DIASXMEDICOS ON MEDICOS.ID_MED = DIASXMEDICOS.ID_DIAXMED JOIN HORARIOMEDICOS ON MEDICOS.ID_MED = IDMED_HRXMED where dia_diaxmed = 'JUEVES'

SELECT HRINICO_HRXMED AS HORAINICIO FROM MEDICOS JOIN DIASXMEDICOS ON MEDICOS.ID_MED = DIASXMEDICOS.ID_DIAXMED JOIN HORARIOMEDICOS ON MEDICOS.ID_MED = IDMED_HRXMED where dia_diaxmed = 'JUEVES'

insert into TURNOS(IDESP_TURNO,DNIMED_TURNO,IDESTADO_TURNO,DNIPAC_TURNO,FECALT_TURNO,HRINICIO_TURNO,HRFIN_TURNO)
value('odontologo',12345,2,67898,now(),'12:00:00','13:00:00');

select * from TURNOS;

select HRINICIO_TURNO,HRFIN_TURNO from TURNOS WHERE FECALT_TURNO = '2023-06-06';

insert into TURNOS(IDESP_TURNO,DNIMED_TURNO,IDESTADO_TURNO,DNIPAC_TURNO,FECALT_TURNO,HRINICIO_TURNO,HRFIN_TURNO)
value('odontologo',12345,2,67898,now(),'12:00:00','13:00:00');

insert into TURNOS(IDESP_TURNO,DNIMED_TURNO,IDESTADO_TURNO,DNIPAC_TURNO,FECALT_TURNO,HRINICIO_TURNO,HRFIN_TURNO) value('odontologo',12345,2,67898,now(),'11:00:00','12:00:00');

select * from TURNOS where FECALT_TURNO = '2023-06-07' order by HRINICIO_TURNO ASC;

delete from TURNOS where ID_TURNO = 9

SELECT NOMBRE_MED, DIA_DIAXMED,HRINICO_HRXMED AS HORAINICIO, HRFIN_HRXMED AS HORAFIN FROM MEDICOS JOIN DIASXMEDICOS ON MEDICOS.ID_MED = DIASXMEDICOS.ID_DIAXMED JOIN HORARIOMEDICOS ON MEDICOS.ID_MED = IDMED_HRXMED

